VsShop/Controllers/PieManagementController.cs
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using VsShop.Models;
using VsShop.ViewModels;

namespace VsShop.Controllers
{
    [Authorize(Roles ="Administrators")]
    public class PieManagementController : Controller
    {
        private readonly IPieRepository _pieRepository;
        private readonly ICategoryRepository _categoryRepository;

        public PieManagementController(IPieRepository pieRepository, ICategoryRepository categoryRepository)
        {
            _pieRepository = pieRepository;
            _categoryRepository = categoryRepository;
        }

        public IActionResult Index()
        {
            var pies = _pieRepository.GetAllPies();
            return View(pies);
        }

        public IActionResult AddPie()
        {
            var categories = _categoryRepository.GetAllCategories();
            var pieEditViewModel = new PieEditViewModel
            {
                Categories = categories.Select(c => new SelectListItem() { Text = c.CategoryName, Value = c.CategoryId.ToString() }).ToList(),
                CategoryId = categories.FirstOrDefault().CategoryId
            };
            return View(pieEditViewModel);
        }

        [HttpPost]
        public IActionResult AddPie(PieEditViewModel pieEditViewModel)
        {
            //Basic validation
            if (ModelState.IsValid)
            {
                pieEditViewModel.Pie.CategoryId = pieEditViewModel.CategoryId;
                _pieRepository.CreatePie(pieEditViewModel.Pie);
                return RedirectToAction("Index");
            }
            return View(pieEditViewModel);
        }

        public IActionResult EditPie(int pieId)
        {
            var categories = _categoryRepository.GetAllCategories();

            var pie = _pieRepository.GetAllPies().FirstOrDefault(p => p.PieId == pieId);

            var pieEditViewModel = new PieEditViewModel
            {
                Categories = categories.Select(c => new SelectListItem() { Text = c.CategoryName, Value = c.CategoryId.ToString() }).ToList(),
                Pie = pie,
                CategoryId = pie.CategoryId
            };

            var item = pieEditViewModel.Categories.FirstOrDefault(c => c.Value == pie.CategoryId.ToString());
            item.Selected = true;

            return View(pieEditViewModel);
        }

        [HttpPost]
        public IActionResult EditPie([Bind("Pie")] PieEditViewModel pieEditViewModel)
        {
            pieEditViewModel.Pie.CategoryId = pieEditViewModel.CategoryId;

            if (ModelState.IsValid)
            {
                _pieRepository.UpdatePie(pieEditViewModel.Pie);
                return RedirectToAction("Index");
            }
            return View(pieEditViewModel);
        }

        [HttpPost]
        public IActionResult DeletePie(int pieId)
        {
            var pie = _pieRepository.GetAllPies().FirstOrDefault(p => p.PieId == pieId);

            if(pie!= null)
            {
                _pieRepository.DeletePie(pie.PieId);
            }

            return RedirectToAction("Index");
        }
    }
}

VsShop/Views/PieManagement/AddPie.cshtml
@model PieEditViewModel

<h2>Create a new pie</h2>

<form asp-controller="PieManagement" asp-action="AddPie" method="post" class="form-horizontal" role="form">
    <h4>Enter the pie details below</h4>
    <hr />
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="Pie.Name" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Pie.Name" class="form-control" />
            <span asp-validation-for="Pie.Name" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Pie.ShortDescription" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Pie.ShortDescription" class="form-control" />
            <span asp-validation-for="Pie.ShortDescription" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Pie.LongDescription" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Pie.LongDescription" class="form-control" />
            <span asp-validation-for="Pie.LongDescription" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Pie.Price" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Pie.Price" class="form-control" />
            <span asp-validation-for="Pie.Price" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Pie.ImageThumbnailUrl" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Pie.ImageThumbnailUrl" class="form-control" />
            <span asp-validation-for="Pie.ImageThumbnailUrl" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Pie.ImageUrl" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Pie.ImageUrl" class="form-control" />
            <span asp-validation-for="Pie.ImageUrl" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Pie.InStock" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Pie.InStock" class="form-control" />
            <span asp-validation-for="Pie.InStock" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Pie.IsPieOfTheWeek" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Pie.IsPieOfTheWeek" class="form-control" />
            <span asp-validation-for="Pie.IsPieOfTheWeek" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Categories" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <select asp-for="CategoryId" class="form-control"
                    asp-items="Model.Categories"></select>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-primary" value="Create pie" />
        </div>
    </div>
</form>

VsShop/Views/PieManagement/EditPie.cshtml
@model PieEditViewModel

<h2>Edit pie</h2>

<form asp-controller="PieManagement" asp-action="EditPie" method="post" class="form-horizontal" role="form">
    <h4>Update the pie details below</h4>
    <hr />
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="Pie.PieId" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Pie.PieId" class="form-control" readonly="readonly" />@*readonly="readonly"*@
            <span asp-validation-for="Pie.PieId" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Pie.Name" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Pie.Name" class="form-control" />
            <span asp-validation-for="Pie.Name" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Pie.ShortDescription" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Pie.ShortDescription" class="form-control" />
            <span asp-validation-for="Pie.ShortDescription" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Pie.LongDescription" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Pie.LongDescription" class="form-control" />
            <span asp-validation-for="Pie.LongDescription" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Pie.Price" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Pie.Price" class="form-control" />
            <span asp-validation-for="Pie.Price" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Pie.ImageThumbnailUrl" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Pie.ImageThumbnailUrl" class="form-control" />
            <span asp-validation-for="Pie.ImageThumbnailUrl" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Pie.ImageUrl" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Pie.ImageUrl" class="form-control" />
            <span asp-validation-for="Pie.ImageUrl" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Pie.InStock" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Pie.InStock" class="form-control" />
            <span asp-validation-for="Pie.InStock" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Pie.IsPieOfTheWeek" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Pie.IsPieOfTheWeek" class="form-control" />
            <span asp-validation-for="Pie.IsPieOfTheWeek" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Categories" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <select asp-for="CategoryId" class="form-control"
                    asp-items="Model.Categories"></select>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-primary" value="Update pie" />
        </div>
    </div>
</form>

VsShop/Views/PieManagement/Index.cshtml
@model IEnumerable<Pie>

<h2>Pie Management</h2>

@if (!Model.Any())
{
    <h3>The shop does not have any pies.</h3>

}
else
{
    <table class="table table-bordered">
        <tr>
            <th>Pie ID</th>
            <th>Image</th>
            <th>Name</th>
            <th>In stock</th>
            <th>Price</th>
            <th>Actions</th>
        </tr>
        @foreach (var pie in Model)
        {
            <tr>
                <td>@pie.PieId</td>
                <td><img src="@pie.ImageThumbnailUrl" /></td>
                <td>@pie.Name</td>
                <td><input type="checkbox" readonly checked="@pie.InStock" /></td>
                <td>@pie.Price</td>
                <td>
                    <form asp-action="DeletePie" asp-route-pieId="@pie.PieId" method="post">
                        <a asp-action="EditPie" asp-route-pieId="@pie.PieId" class="btn btn-primary">Edit</a>
                        <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Do you really want to delete this pie?');">
                            Delete
                        </button>
                    </form>
                </td>
            </tr>
        }
        </table>
}

<a class="btn btn-primary" asp-action="AddPie">Add new pie</a>